const CARD_WIDTH_NUM = 100;
const CARD_WIDTH = CARD_WIDTH_NUM + "px";
const WIDTH_TO_HEIGTH = 1.39583;
const CARD_HEIGHT_NUM = CARD_WIDTH_NUM * WIDTH_TO_HEIGTH;
const CARD_HEIGHT = CARD_HEIGHT_NUM + "px";